text_list = {
    'Ukrainian': {
        "nousername": "Для коректної роботи бота потрібно, щоб у вас був встановлений @username",
        "setname": "Напиші ім'я, його будуть бачити інші користувачі",
        "nameerror": "Довжина імені повинна бути в межах між 2 та 50 символів, ви ввели символів: ",
        "setdesc": "Напиші опис до свого акаунту, його будуть бачити інші користувачі. Можна пропустити цей пункт",
        "deskerror": "Довжина опису повинна бути в межах між 2 та 1000 символів, ви ввели символів: ",
        "skipdesc": "Пропустити",
        "setage": "Скільки тобі років?",
        "ageerror": "Вік повинен бути цифрою та бути в межах від 10 до 100 років",
        "setgender": "Твоя стать",
        "setcity": "З якого ти міста? Якщо показує не твоє місто, то можна вказати більш конкретно. \nНаприклад: \nЛиман - локація буде вказана як Франція \nЛиман Україна - локація буде вказана як Україна",
        "cityerror": "Не можливо знайти місто, спробуйте ще раз",
        "setpurpose": "Що ти бажаєшь знайти завдяки боту? Ти будеш бачити людей з іншою метою, як і вони тебе",
        "setuserinterests": "Обери щонайменше один інтерес і далі нажми кнопку 'Далі' (максимум 5)",
        "interestsDone": "Далі",
        "gendersDone": "Готово",
        "userinterestserror": "Потрібно обрати щонайменше один інтерес",
        "userinterestserror2": "Максимум може бути 5 інтересів",
        "deleteprofile": "Видалити мій профіль",
        "setphoto": "Відправ фото свого профіля",
        "showinterests": "Інтереси",
        "changeprofile": "Змінити інформацію про себе",
        "setlangbtn": "Змінити мову в боті",
        "setnamebtn": "Змінити ім'я",
        "setdescbtn": "Змінити опис",
        "setagebtn": "Змінити вік",
        "setgenderbtn": "Змінити стать",
        "setcitybtn": "Змінити місто",
        "setpurposebtn": "Змінити мету пошуку",
        "setuserinterestsbtn": "Змінити інтереси",
        "setphotobtn": "Змінити фото профілю",
        "agefilter": "Проміжок віку, в котрому здійснувати пошук ",
        "distancefilter": "Максимальна можлива відстань пошуку",
        "km": "км",
        "genderfilter": "Пошук людей за статтю",
        "interestfilter": "Пошук людей за інтересом",
        "nointerestfilter": "Будь які",
        "nogenderfilter": "Будь які",
        "myfilters":"Мої фільтри",
        "changeminagefilter": "Змінити мінімальний рік пошуку",
        "changemaxagefilter": "Змінити максимальний рік пошуку",
        "changemaxdestancefilter": "Змінити максимальну дистанцію пошуку",
        "changegenderfilter": "Змінити за якою статтю здійснувати пошук",
        "changeinterestsfilter": "Змінити за якими інтересами здійснувати пошук",
        "setminagefilter": "Як працює пошук за віком?\n\nВи будете бачити лише людей, котрі знаходяться в межах вашого пошуку, і ви знаходитесь в межах їх пошуку\n\nВас не зможуть знайти люди, котрі не підпадають під межі вашого пошуку\n\n\nВведіть мінімальний вік для пошуку",
        "setmaxagefilter": "Як працює пошук за віком?\n\nВи будете бачити лише людей, котрі знаходяться в межах вашого пошуку, і ви знаходитесь в межах їх пошуку\n\nВас не зможуть знайти люди, котрі не підпадають під межі вашого пошуку\n\n\nВведіть максимальний вік для пошуку",
        "setmaxdistancefilter": "Як працює пошук за дистанцією?\n\nВи будете бачити лише людей, котрі знаходяться в межах вашого пошуку, і ви знаходитесь в межах їх пошуку\n\nВас не зможуть знайти люди, котрі не підпадають під межі вашого пошуку\n\n\nВведіть максимальну дистанцію для пошуку, якщо бажаєте шукати людей лише в межах свого міста - напишіть 0",
        "setgenderfilter": "Як працює пошук за статтю?\n\nВи будете бачити лише людей, котрі знаходяться в межах вашого пошуку, і ви знаходитесь в межах їх пошуку\n\nВас не зможуть знайти люди, котрі не підпадають під межі вашого пошуку\n\n\nОберіть варіанти котрі підходять для вас та нажміть 'Готово'",
        "setinterestsfilter": "Як працює пошук за інтересами?\n\nВи будете бачити лише людей, котрі знаходяться в межах вашого пошуку\n\nВас будуть й надалі бачити люди, котрі не підпадають під межі вашого пошуку\n\n\nОберіть варіанти котрі підходять для вас та нажміть 'Готово'",
        "minagefiltererror": "Мінімальний вік повинен бути цифрою, бути в межах від 10 до 100 років та бути менше чим максимальний вік",
        "maxagefiltererror": "Максимальний вік повинен бути цифрою, бути в межах від 10 до 100 років та бути більше чим мінімальний вік",
        "maxdistancefiltererror": "Максимальна дистанція повинна бути цифрою та бути в межах від 0 до 1500 км",
        "userinterestsfiltererror2": "Максимум можна шукати людей за один інтересом",
        "startsearching": "Дивитись анкети",
        "nopeople":"Нема анкет, які підходят від критерії пошуку повертаюсь в головне меню",
        "yousetdis": "Ви пропустили анкету",
        "yousetlik": "Ви відправили лайк",
        "yougetlike": "Ви отримали лайк! Подивитись всі нові заявки можна на головній сторінці! ",
        "nonewlikes": "Нема заявок на спілкування",
        "nolike": "Нема на що дивитись!",
        "nomorelikes": "Заявки закінчились!",
        "newmutual": "Новий взаємний лайк!",
        "mynewlikes": "Нових заявок: ",
        "back": "Назад",
        "repeat": "Повторити спробу",
        "unknown_command": "Я не розумію"
    },

    'Russian': {
        "nousername": "Для правильной работы бота нужно, чтобы у вас был установлен @username",
        "setname": "Напиши имя, его будут видеть другие пользователи",
        "nameerror": "Длинна имени должна быть между 2 и 50 символами, вы ввели символов: ",
        "setdesc": "Напиши описание у своей анкете, его будут видеть другие пользователи. Можно пропустить этот пункт",
        "deskerror": "Длинна описания должна быть между 2 и 1000 символами, вы ввели символов: ",
        "skipdesc": "Пропустить",
        "setage": "Сколько тебе лет?",
        "ageerror": "Возраст должен быть цифрой в пределах от 10 до 100 лет",
        "setgender": "Твой пол",
        "setcity": "С какого ты города? Если неправильно отображается город, можно уточнить \nНапример: \nЛиман - локация будет указана как Франция \nЛиман Украина - локация будет указана как Украина",
        "cityerror": "Не возможно найти твой город попробуй ещё раз",
        "setpurpose": "Что ты хочешь найти благодаря боту? Ты будешь видеть людей с другой целью, как и они тебя",
        "setuserinterests": "Выбери как минимум 1 интерес и нажми кнопку 'Далее' (максимум 5)",
        "interestsDone": "Далее",
        "gendersDone": "Готово",
        "userinterestserror": "Нужно выбрать как минимум один интерес",
        "userinterestserror2": "Максимум можно выбрать 5 интересов",
        "deleteprofile": "Удалить мой профиль",
        "setphoto": "Отправь фото своего профиля",
        "showinterests": "Интересы",
        "changeprofile": "Изменить информацию про себя",
        "setlangbtn": "Изменить язык в боте",
        "setnamebtn": "Изменить имя",
        "setdescbtn": "Изменить описание",
        "setagebtn": "Изменить возраст",
        "setgenderbtn": "Изменить пол",
        "setcitybtn": "Изменить город",
        "setpurposebtn": "Изменить цель поиска",
        "setuserinterestsbtn": "Изменить инересы",
        "setphotobtn": "Изменить фото профиля",
        "agefilter": "Промежуток, в котором производить поиск по возрасту ",
        "distancefilter": "Максимальное расстояние поиска",
        "km": "км",
        "genderfilter": "Поиск людей по полу",
        "interestfilter": "Поиск людей по интересу",
        "nointerestfilter": "Любой",
        "nogenderfilter": "Любой",
        "myfilters":"Мои фильтры",
        "changeminagefilter": "Изменить минимальный возраст",
        "changemaxagefilter": "Изменить максимальный возраст",
        "changemaxdestancefilter": "Изменить максимальную дистанцию",
        "changegenderfilter": "Изменить пол, по которому производить поиск",
        "changeinterestsfilter": "Изменить интерес, по которому производить поиск",
        "setminagefilter": "Как работает поиск по возрасту?\n\nВы видите только тех людей, которые находяться в границах вашего поиска, и вы находитесь в границах их поиска\n\nВас не смогут найти люди, которые не подходят под границы вашего поиска\n\n\nУкажите минимальный возраст по которому производить поиск",
        "setmaxagefilter": "Как работает поиск по возрасту?\n\nВы видите только тех людей, которые находяться в границах вашего поиска, и вы находитесь в границах их поиска\n\nВас не смогут найти люди, которые не подходят под границы вашего поиска\n\n\nУкажите максимальный возраст по которому производить поиск",
        "setmaxdistancefilter": "Как работает поиск по дистанции?\n\nВы видите только тех людей, которые находяться в границах вашего поиска, и вы находитесь в границах их поиска\n\nВас не смогут найти люди, которые не подходят под границы вашего поиска\n\n\nУкажите максимальную дистанцию по которому производить поиск, если хотите видеть людей только из своего города - введите 0",
        "setgenderfilter": "Как работает поиск по полу?\n\nВы видите только тех людей, которые находяться в границах вашего поиска, и вы находитесь в границах их поиска\n\nВас не смогут найти люди, которые не подходят под границы вашего поиска\n\n\nУкажите варианты, которые подходят и нажми 'Готово'",
        "setinterestsfilter": "Как работает поиск по интересу?\n\nВы видите только тех людей, которые находяться в границах вашего поиска\n\nВас и дальше будут видеть люди, которые не походят под границы вашего поиска\n\n\nУкажите варианты, которые подходят и нажми 'Готово'",
        "minagefiltererror": "Минимальный возраст должен быть цифрой, быть в границах между от 10 до 100 лет и быть меньше чем максимальный возраст",
        "maxagefiltererror": "Максимальный возраст должен быть цифрой, быть в границах между от 10 до 100 лет и быть больше чем максимальный возраст",
        "maxdistancefiltererror": "Максимальная дистанция должна быть цифрой и быть в границах от 0 до 1500 км",
        "userinterestsfiltererror2": "Максимум можно искать по одному интересу",
        "startsearching": "Смотреть анкеты",
        "nopeople":"Нет анкет, которые подходят под критерии поиска, возвращаюсь в главный экран",
        "yousetdis": "Вы пропустили анкету",
        "yousetlik": "Вы отправили лайк",
        "yougetlike": "Вы получили новую заявку на общение! Посмотреть все заявки на общение можно на главной странице! ",
        "nonewlikes": "Нет заявок на общение",
        "nolike": "Нет на что смотреть!",
        "nomorelikes": "Заявки закончились!",
        "newmutual": "Новый взаимный лайк!",
        "mynewlikes": "Новых заявок: ",
        "back": "Назад",
        "repeat": "Повторить попытку",
        "unknown_command": "Я не понимаю"
    },
    'English': {
        "nousername": "You need to have @username set for the bot to work properly",
        "setname": "Write a name so other users can see it",
        "nameerror": "Name must be between 2 and 50 characters, you entered characters: ",
        "setdesc": "Write a description for your profile, other users will see it. You can skip this part",
        "deskerror": "Description length must be between 2 and 1000 characters, you entered characters: ",
        "skipdesc": "Skip",
        "setage": "How old are you?",
        "ageerror": "Age must be a number between 10 and 100",
        "setgender": "Your gender",
        "setcity": "What city are you from? If the city is displayed incorrectly, you can specify \nFor example: \nLiman - the location will be listed as France \nLiman Ukraine - the location will be listed as Ukraine",
        "cityerror": "Unable to find your city, please try again",
        "setpurpose": "What do you want to find? You will see people with a different purpose, just like they see you",
        "setuserinterests": "Select at least 1 interest and click 'Next' (max 5)",
        "interestsDone": "Next",
        "gendersDone": "Done",
        "userinterestserror": "You must select at least one interest",
        "userinterestserror2": "Maximum 5 interests can be selected",
        "deleteprofile": "Delete my profile",
        "setphoto": "Send your profile photo",
        "showinterests": "Interests",
        "changeprofile": "Change profile information",
        "setlangbtn": "Change bot language",
        "setnamebtn": "Change name",
        "setdescbtn": "Edit description",
        "setagebtn": "Change age",
        "setgenderbtn": "Change gender",
        "setcitybtn": "Change city",
        "setpurposebtn": "Change search purpose",
        "setuserinterestsbtn": "Change interests",
        "setphotobtn": "Change profile photo",
        "agefilter": "Gap in which to search by age ",
        "distancefilter": "Max search distance",
        "km": "km",
        "genderfilter": "Search people by gender",
        "interestfilter": "Search people by interest",
        "nointerestfilter": "Any",
        "nogenderfilter": "Any",
        "myfilters":"My filters",
        "changeminagefilter": "Change min age",
        "changemaxagefilter": "Change max age",
        "changemaxdestancefilter": "Change max distance",
        "changegenderfilter": "Change gender to search",
        "changeinterestsfilter": "Change interest to search",
        "setminagefilter": "How does search by age work?\n\nYou only see people that are within your search scope, and you are within their search scope\n\nYou won't be found by people who don't match your search scope \n\n\nSpecify the minimum age to search for",
        "setmaxagefilter": "How does search by age work?\n\nYou only see people that are within your search scope, and you are within their search scope\n\nYou won't be found by people who don't match your search scope \n\n\nSpecify the maximum age for which to search",
        "setmaxdistancefilter": "How does distance search work?\n\nYou only see people that are within your search scope, and you are within their search scope\n\nYou won't be found by people who don't match your search scope \n\n\nSpecify the maximum distance at which to search, if you want to see people only from your city - enter 0",
        "setgenderfilter": "How does gender search work?\n\nYou only see people that are within your search scope, and you are within their search scope\n\nYou can't be found by people that don't match your search scope \n\n\nSelect the options that apply and click 'Finish'",
        "setinterestsfilter": "How does search by interest work?\n\nYou only see people who are within your search scope\n\nYou will continue to be seen by people who are not within your search scope\n\n\nSpecify options that match and click 'Done'",
        "minagefiltererror": "Minimum age must be a numeric value, between 10 and 100 years old, and less than the maximum age",
        "maxagefiltererror": "Max age must be a numeric value, between 10 and 100 years old, and greater than max age",
        "maxdistancefiltererror": "Maximum distance must be a number and be between 0 and 1500 km",
        "userinterestsfiltererror2": "Maximum searchable per one interest",
        "startsearching": "View profiles",
        "nopeople":"There are no profiles that match the search criteria, I return to the main screen",
        "yousetdis": "Missed",
        "yousetlik": "Like",
        "yougetlike": "You have received a new communication request! You can see all communication requests on the main page!",
        "nonewlikes": "No requests to chat",
        "nolike": "Nothing to look at!",
        "nomorelikes": "No more requests!",
        "newmutual": "New Mutual Like!",
        "mynewlikes": "New likes: ",
        "back": "Back",
        "repeat": "Retry",
        "unknown_command": "I don't understand"
    }
    
}